eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    hostname: localhost

# Management & actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

microservice:
  usermanagement-service:
    endpoints:
      endpoint:
        uri: lb://USERMANAGEMENT/api/user/getSubUserInfo
  security-service:
    endpoints:
      endpoint:
        uri: http://Security-Service/security/login
