eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://usermanagement/api/user/findByEmail
  order-service:
    endpoints:
      endpoint:
        uri: http://Security-Service/security/login


